name: torch
channels:
  - defaults
  - conda-forge
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - certifi=2025.10.5
  - fsspec=2025.7.0
  - importlib-metadata=8.5.0
  - libexpat=2.7.1
  - libffi=3.4.4
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - ncurses=6.5
  - nomkl=3.0
  - openssl=3.5.4
  - opentelemetry-api=1.37.0
  - python=3.12.8
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - wheel=0.45.1
  - zipp=3.21.0
  - zlib=1.3.1
  - pip:
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.20.0
      - fonttools==4.60.1
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.5
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.3.2
      - packaging==25.0
      - pandas==2.3.2
      - pillow==12.0.0
      - pip==25.3
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - six==1.17.0
      - sympy==1.14.0
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchvision==0.23.0
      - tzdata==2025.2
prefix: /Users/danielrojas/miniconda3/envs/torch
